### ISSUE TITLE
Task List 02-12-17

### ISSUE THREAD

**Issue by louis-ver** [louis-ver/control#1]
- [ ] Add URL parsing (make sure URL is valid. Add, remove www)
  - Both www and no www URL must be added to /host
- [ ] Figure out how to sudo write to host
- [ ] Add scheduler event to remove website x hours after add
